### ISSUE TITLE
add healthchecks

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/docker#4]
to images ? https://docs.docker.com/engine/reference/builder/#healthcheck

in compose file ? https://docs.docker.com/compose/compose-file/#healthcheck

**Comment by Vampouille** [comment]
I would prefer in Dockerfile, so we can override it in docker-compose file.

**Comment by fvanderbiest** [comment]
That's the point of georchestra/georchestra#1870 for ldap and db

**Comment by RemiDesgrange** [comment]
Correct me if I'm wrong but I don't think putting health check inside the Dockerfile of apps would be a good idea. From our production POV, if app crash, then the container is restarted (and the JVM doesn't crash very often). If the DB/LDAP crash, which does not happen often too. Then these services are restarted. The only point where I could find interesting to have health check and restart container is when the number of connection to the DB goes too high. But this could lead to service disruption unpredictable. And this issue is more of a misconfig of the db connection pool.

**Comment by jeanmi151** [comment]
This is done here: https://github.com/georchestra/docker/commit/817973b8dfe790f8cdc2933b5017fe26a5de78ee
I guess we can close !
