### ISSUE TITLE
unavailable image tags on 20.1 branch

### ISSUE THREAD

**Issue by jeanpommier** [georchestra/docker#76]
docker-compose features georchestra containers with 20.1.x tag
But this tag is not available. If we look on dockerhub, available tag is 20.1.0

**Comment by RemiDesgrange** [comment]
I think I spoted the error:
here: https://github.com/georchestra/georchestra/blob/20.1.x/.github/workflows/ldap.yml#L35-L39

We don't execute this code, because the `ldap/**` folder did not contain changes. We can:

* manually build and push this image
* touch a file in the `ldap` dir to trigger a build.

**Comment by fvanderbiest** [comment]
What are the missing images ? All of them or just ldap ?

**Comment by RemiDesgrange** [comment]
A lot of them:

* cas
* sp
* header
* db
* ldap
* console

**Comment by fvanderbiest** [comment]
I think this one has been addressed.
